- project:
    templates:
      - check-requirements
      - publish-openstack-docs-pti
      - openstack-python-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - lib-forward-testing
      - lib-forward-testing-python3
      - release-notes-jobs-python3
